# Generated by Django 5.1.1 on 2024-10-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_staff_profile_customer_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Profile_Images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
